### ISSUE TITLE
Clear URL parameters option

### ISSUE THREAD

**Issue by gnevan** [TrianguloY/SimpleClipboardEditor#12]
Hello!

I would like to suggest an enhancement that is crucial to me. Most of the time working with the links through a clipboard a have a task to clear all the tracking parameters from URLs.

I think it would be super handy to have an option to automatically clear them in this app. For example if I copied some url (or opened your app through a context menu) and have such an option set, the app will check if it looks like an URL and clear all after and including the "?" sign.

I don't know if it is hard to implement. 

Thanks for the app!

**Comment by TrianguloY** [comment]
For a moment I was confused, because that's one of the features of my app https://github.com/TrianguloY/UrlChecker
This app is just a textview syncronized with the clipboard, for quick view/edit. For url related features I think that other apps will be a way better fit.

With that app you can open the url on the clipboard (there is a shortcut, but you can also share or even open it) and it can automatically remove only the tracking parameters, or even manually all parameters.
Then you can open or share the edited url (or even copy back to clipboard)

Duplicating that functionality is probably not a good idea. And even though it is maybe faster that opening that other app, I think the extra features are worth it. Plus maybe in the future I can add automation which may allow for a one-click clipboard cleanup (but that's not probably going to happen in the near future, sorry).

I hope this helps you, sorry for the "don't use this, use this instead" response but I think this case is justified.

**Comment by gnevan** [comment]
Oh, I did not know it is already implemented as a separate app! That is the app I initially searched for. Definitely no need to duplicate it here. There are a lot of handy url functions (modules)! Thank you!

**Comment by TrianguloY** [comment]
Glad it helped! 
I'm going to close this then 🙂
