### ISSUE TITLE
Add quick way to open app?

### ISSUE THREAD

**Issue by achou11** [TrianguloY/SimpleClipboardEditor#4]
This is a cool project! I appreciate its simplicity and ease of use. I personally would love it if there was quicker way to open the app to view and edit the contents of my clipboard. A couple of potential examples include:

- a persistent/silent notification when the clipboard has something in it

- adding an option to the context menu i.e. when long pressing an input and the options for copy, paste, etc show up

**Comment by achou11** [comment]
just noticed that there's a shortcut action to clear the clipboard. super handy! only problem is that with my launcher, I don't have the app icon readily available to make this a quick action for me, so still think there's some value to the other ideas I offered

**Comment by TrianguloY** [comment]
The notification is probably impossible due to the clipboard restrictions. An app can't (in normal circumstances) check the clipboard in the background. The notification in that case would be just like a shortcut, and I think there are apps to create static notifications with custom shortcuts.

The context menu feature should be handy! I'll investigate if it can be made and how.

About the clear shortcut: if you long tap the shortcut doesn't it allow you to move it to the desktop? In any case it is not showing in the list with other apps, maybe I didn't configured it correctly. I'll check it.

**Comment by achou11** [comment]
> The notification in that case would be just like a shortcut, and I think there are apps to create static notifications with custom shortcuts.

Ah yeah this is what I meant by the notification (basically a shortcut to just open the app). You're right about just using a separate app, but then I have to install a separate app 😜

> About the clear shortcut: if you long tap the shortcut doesn't it allow you to move it to the desktop?

yep it does! I'm just... selective... about what I display in my primary app list so it isn't necessarily my first instinct to add it 😄

**Comment by uli-on** [comment]
I can't tell whether this is the spot where the feature "copy selection to clipboard, edit, and paste back on closing" originated from (just an assumption), but however it was:

# Huge  (H-999 size) thanks

to you, @TrianguloY, and probably also to you, @achou11! 

This is so brilliant for editing messages in damn too small messenger text fields with f...g small 12px fonts! Whoah, what a relief, what a joy, again, to write more than just a standard tweet!! Deeeep bow!

**Comment by achou11** [comment]
@uli-on oh i didn't even notice that new feature until you mentioned it, but damn yeah that's awesome! agree that it's super useful and honestly basically addresses the issue i was facing when i initially created this issue 😄

@TrianguloY feel free to close this if you feel like it - pretty happy with this solution!

**Comment by TrianguloY** [comment]
Yup, it was! (Although I forgot to tag the commit, oops). Glad you find it useful :)

Turns out adding the option was possible and easy, thanks for the idea! 

As I said originally, the notification is not possible (just a shortcut... like those in the quick actions bar...hmmm) so I'm closing this as completed.
